In [7]:
import numpy as np
from scipy.signal import convolve2d

A = np.arange(9).reshape(3,3)

In [4]:
B = np.arange(2,6).reshape(2,2)

In [5]:
B

array([[2, 3],
       [4, 5]])

In [32]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
convolve2d(A,np.rot90(B,k=2), mode='valid')

array([[35, 49],
       [77, 91]])

In [42]:
H = np.zeros(4).reshape(2,2)
for i in range(B.shape[0]):
    for j in range(B.shape[1]):
        A_mini = A[i:i+2,j:j+2]
        print(A[i:i+2,j:j+2])
        H[i,j] = np.sum(np.array(B)*np.array(A_mini))

[[0 1]
 [3 4]]
[[1 2]
 [4 5]]
[[3 4]
 [6 7]]
[[4 5]
 [7 8]]


In [43]:
H

array([[ 35.,  49.],
       [ 77.,  91.]])

In [44]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
A = np.ones((1,1,3,3))

In [48]:
A

array([[[[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]]])

In [52]:
np.pad(A, ((0,0), (0,0), (2,2), (2,2)), 'constant')

array([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
         [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
         [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

In [76]:
4//2

2

In [107]:
class MaxPoolingLayer():

    def __init__(self, kernel_size=2):
        self.kernel_size = kernel_size

    def fprop(self, inputs):
        N, num_input_channels, input_dim_1, input_dim_2 = inputs.shape
        output_dim_1 = int((input_dim_1-self.kernel_size)/2)+1
        output_dim_2 = int((input_dim_2-self.kernel_size)/2)+1
        outputs = np.empty((N, num_input_channels, output_dim_1, output_dim_2))
        self.mask = np.zeros_like(inputs)
        for n in range(N):
            for c in range(num_input_channels):
                for i in range(output_dim_1):
                    for j in range(output_dim_2):
                        outputs[n,c,i,j] = np.max(inputs[n,c,2*i:2*i+self.kernel_size, 2*j:2*j+self.kernel_size])
                        argmax = np.argmax(inputs[n,c,2*i:2*i+self.kernel_size, 2*j:2*j+self.kernel_size])
                        row = argmax//self.kernel_size + 2*i
                        col = argmax % self.kernel_size + 2*j
                        self.mask[n,c,row,col] = 1
                        
        return outputs
    
    def bprop(self, inputs, outputs, grads_wrt_outputs):
        print(inputs.shape, outputs.shape, grads_wrt_outputs.shape, self.mask.shape)
        grads = np.zeros_like(inputs)
        grads[self.mask] = grads_wrt_outputs
        return grads

In [108]:
A = np.arange(64).reshape(1,1,8,8)

In [109]:
A

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29, 30, 31],
         [32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47],
         [48, 49, 50, 51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60, 61, 62, 63]]]])

In [110]:
mp = MaxPoolingLayer(2)

In [111]:
B = mp.fprop(A)

In [112]:
np.sum(mp.mask)

16

In [113]:
mp.bprop(A,B,B)

(1, 1, 8, 8) (1, 1, 4, 4) (1, 1, 4, 4) (1, 1, 8, 8)


ValueError: shape mismatch: value array of shape (1,1,4,4) could not be broadcast to indexing result of shape (1,1,8,8,1,8,8)

In [104]:
np.__version__

'1.13.1'